### ISSUE TITLE
How to publish mongo cursor to the client side?

### ISSUE THREAD

**Issue by minixxie** [andrei-markeev/ddpserver#1]
Hi Andrey,

Your repo sounds great! I'd like to have a try. I'm already familiar with the meteor.js way, but when I looked into your example, I couldn't figure out how something this could be done in the server side with your library:
Meteor.publish( "Something", function() {
      return SomeMongoCollection.find(...);
});
Could you give me some hints? Thanks very much.
From the stack overflow, you've mentioned that this library should be able to give "live data"? (http://stackoverflow.com/questions/31063728/a-ddp-server-in-c)

Thanks & Regards,
Simon

**Comment by andrei-markeev** [comment]
Hi Simon,

Thanks for your feedback, really appreciated! :)

Here's an example how you do the live data.

First, in your Meteor site, you need to create a connection to your c++ app, and then define a mongo collection specifying the connection object:

``` js
if (Meteor.isClient)
{
    Meteor.startup(function() {
        // this connects to the c++ backend
        MyConnection = DDP.connect("http://localhost:9002");
        // now let's define a collection
        ExternalCollection = new Mongo.Collection("coll1", { connection: MyConnection });
    });
}
```

So now Meteor has connection from client to your c++ ddp server, and it knows that ExternalCollection is served over this connection.

After that, you just use the collection somewhere.
For example if you use Iron router, it could be like this:

``` js
Router.route('/myPage/:_id', function () {
    this.render('myTemplate', {
        data: function () {
            return ExternalCollection.findOne({_id: this.params._id});
        }
    });
});
```

And let's say you have the following template "myTemplate":

``` html
<template name="myTemplate">
   <div>Hello world from {{serverVar}}!</div>
</template>
```

Now on c++ side, you do something like this:

``` c++
jvar::Variant data;
data.createObject();
data.addProperty("serverVar", "ddp server");
ddpServer->emitAdd("coll1", "element1_id", data);
```

And voila, now if you navigate to `/myPage/element1_id`, you will see

```
Hello world from ddp server!
```

Subscriptions and publications in Meteor serve as a way to limit the amount of data send over the wire. So that if you're on some page that doesn't display ExternalCollection, then data is not coming. As of yet, support for subscriptions and publications is missing in ddpserver, so all the data is sent to all clients as soon as it is emited. Support for subscriptions will be added soon, for now you can emulate it with methods if necessary.

More info and complete examples of server-side code can be found in `README.md` and in `/examples` folder in this repository.

If you have more questions, please ask!

**Comment by andrei-markeev** [comment]
I re-read your question and it seems you're asking if one can publish live data from C++ in a same "magic" fashion as we do from Meteor.

Well the answer is, no, you have to do it manually. Every time your data is updated or there's something added or deleted, then you should issue **emitChange**, **emitAdd**, or **emitRemove** correspondingly, example here: https://github.com/andrei-markeev/ddpserver#live-data

Also, if you want to connect to a Mongo db, then you don't need c++ probably, just connect to it from the Meteor backend, and then you can do cursors. This SO answer explains how you can connect to multiple Mongo databases from Meteor backend: http://stackoverflow.com/a/20537457/361687
